#!/bin/sh
g77 -g  -c gexam3.F
g++ -c -g -I../TGeant3 -I$ROOTSYS/include gmain.C
g++ -o gexam3 gmain.o gexam3.o `root-config --glibs` \
-lVMC -lPhysics -lEG -lEGPythia6 -lGeom $PYTHIA6/libPythia6.so \
-L../lib/tgt_Linux/ -lgeant321 -L$CERNLIB -lpacklib -lg2c
